services:
  naminter:
    build:
      context: .
      dockerfile: Dockerfile
    image: naminter:latest
    volumes:
      - ./output:/app/output
      - ./responses:/app/responses
      - ./custom-lists:/app/custom-lists
