services:
  naminter:
    build:
      context: .
      dockerfile: Dockerfile
    image: naminter:latest
    volumes:
      - ./results:/app/results
      - ./responses:/app/responses
      - ./lists:/app/lists
