[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "naminter"
dynamic = ["version", "description", "authors", "license"]
readme = "README.md"
requires-python = ">=3.11"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Internet",
    "Topic :: Utilities"
]

dependencies = [
    "click>=8.2.1",
    "curl-cffi>=0.13.0",
    "aiofiles>=24.1.0",
    "jinja2>=3.1.6",
    "jsonschema>=4.25.0",
    "rich>=14.1.0",
    "rich-click>=1.8.9",
    "weasyprint>=66.0"
]

maintainers = [{ name = "3xp0rt" }]

keywords = [
    "osint",
    "username",
    "availability",
    "checker",
    "whatsmyname",
    "reconnaissance",
    "cybersecurity",
    "investigation",
    "naminter"
]

[project.urls]
Homepage     = "https://github.com/3xp0rt/naminter"
Repository   = "https://github.com/3xp0rt/naminter"
BugTracker   = "https://github.com/3xp0rt/naminter/issues"
Documentation= "https://github.com/3xp0rt/naminter#readme"
Source       = "https://github.com/3xp0rt/naminter"

[project.scripts]
naminter = "naminter.cli.main:entry_point"

[tool.setuptools.dynamic]
version = {attr = "naminter.__version__"}
description = {attr = "naminter.__description__"}
authors = [
    {name = "naminter.__author__", email = "naminter.__author_email__"}
]
license = {text = "naminter.__license__"}

[tool.setuptools]
package-dir = {"" = "."}
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["naminter*"]

[tool.setuptools.package-data]
"naminter.cli.templates" = ["*.html"]
"naminter" = ["cli/templates/*.html"]
